set_property PACKAGE_PIN E3 [get_ports clk_i]
set_property IOSTANDARD LVCMOS33 [get_ports clk_i]
create_clock -period 10.000 -name sys_clk_pin -waveform {0.000 5.000} [get_ports clk_i]

set_property PACKAGE_PIN N17 [get_ports rst_i]
set_property IOSTANDARD LVCMOS33 [get_ports rst_i]

set_property PACKAGE_PIN J15 [get_ports {in_data_i[0]}]
set_property PACKAGE_PIN L16 [get_ports {in_data_i[1]}]
set_property PACKAGE_PIN M13 [get_ports {in_data_i[2]}]
set_property PACKAGE_PIN R15 [get_ports {in_data_i[3]}]
set_property PACKAGE_PIN R17 [get_ports {in_data_i[4]}]
set_property PACKAGE_PIN T18 [get_ports {in_data_i[5]}]
set_property PACKAGE_PIN U18 [get_ports {in_data_i[6]}]
set_property PACKAGE_PIN R13 [get_ports {in_data_i[7]}]
set_property PACKAGE_PIN T8  [get_ports {in_data_i[8]}]
set_property PACKAGE_PIN U8  [get_ports {in_data_i[9]}]
set_property PACKAGE_PIN R16 [get_ports {in_data_i[10]}]
set_property PACKAGE_PIN T13 [get_ports {in_data_i[11]}]
set_property PACKAGE_PIN H6  [get_ports {in_data_i[12]}]
set_property PACKAGE_PIN U12 [get_ports {in_data_i[13]}]
set_property PACKAGE_PIN U11 [get_ports {in_data_i[14]}]
set_property PACKAGE_PIN V10 [get_ports {in_data_i[15]}]

set_property IOSTANDARD LVCMOS33 [get_ports {in_data_i[*]}]

set_property PACKAGE_PIN P17 [get_ports is_init_floors_i]
set_property IOSTANDARD LVCMOS33 [get_ports is_init_floors_i]

set_property PACKAGE_PIN M17 [get_ports is_init_resistance_i]
set_property IOSTANDARD LVCMOS33 [get_ports is_init_resistance_i]

set_property PACKAGE_PIN H17 [get_ports last_broken_o]
set_property IOSTANDARD LVCMOS33 [get_ports last_broken_o]

set_property PACKAGE_PIN T10 [get_ports {o_seg_o[0]}]
set_property PACKAGE_PIN R10 [get_ports {o_seg_o[1]}]
set_property PACKAGE_PIN K16 [get_ports {o_seg_o[2]}]
set_property PACKAGE_PIN K13 [get_ports {o_seg_o[3]}]
set_property PACKAGE_PIN P15 [get_ports {o_seg_o[4]}]
set_property PACKAGE_PIN T11 [get_ports {o_seg_o[5]}]
set_property PACKAGE_PIN L18 [get_ports {o_seg_o[6]}]
set_property PACKAGE_PIN H15 [get_ports {o_seg_o[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_seg_o[*]}]

set_property PACKAGE_PIN J17 [get_ports {o_sel_o[0]}]
set_property PACKAGE_PIN J18 [get_ports {o_sel_o[1]}]
set_property PACKAGE_PIN T9  [get_ports {o_sel_o[2]}]
set_property PACKAGE_PIN J14 [get_ports {o_sel_o[3]}]
set_property PACKAGE_PIN P14 [get_ports {o_sel_o[4]}]
set_property PACKAGE_PIN T14 [get_ports {o_sel_o[5]}]
set_property PACKAGE_PIN K2  [get_ports {o_sel_o[6]}]
set_property PACKAGE_PIN U13 [get_ports {o_sel_o[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_sel_o[*]}]
